### ISSUE TITLE
Missing role for route members

### ISSUE THREAD

**Issue by Bibi56** [osm-fr/osmose-backend#494] opened 2019-04-30 15:46 UTC
According to the [wiki](https://wiki.openstreetmap.org/wiki/Relation:route), the first role for members of routes is empty (not road).
So it's a bad advice to request a role for members of such relations (type=route).

Item : 1140.

[Example](https://osmose.openstreetmap.fr/fr/map/#item=1140&zoom=17&lat=47.941729&lon=-1.230265&level=3&tags=&fixable=)

**Comment by frodrigo** [comment] 2019-04-30 15:59
It's a generic rule for all relations.

The tag-less way is a duplicate of the real ways. The tag-less way should not be present.

**Comment by Bibi56** [comment] 2019-04-30 16:22
This generic rule is explicitly in contradiction with the wiki for routes:


Way/node | Role | Recurrence | Discussion
-- | -- | -- | --
  | <nowiki>&lt;empty&gt;</nowiki> | ! 1+ | The ways making up the route. Currently the empty role should be used instead of the route role, which was used sometimes with PTv1.

**Comment by frodrigo** [comment] 2019-04-30 16:24
I don't think so. The way part of the route should be some kind of way, so with tags to describe them.

**Comment by Bibi56** [comment] 2019-04-30 16:51
I'm not saying I disagree with you but the sole role for this purpose was road and it is depreciated now. Which indeed has its logic: the route _consists_ of ways, the members, they decided to use the default empty role for that. Only different roles have to be explicit.

**Comment by frodrigo** [comment] 2019-05-01 00:10
Ok for empty role. The way part of the route should have tags. This ways are at least `highway=*`.

**Comment by frodrigo** [comment] 2019-05-05 12:46
Please, reopen if required.

**Closed by frodrigo** 2019-05-05 12:46 UTC
