### ISSUE TITLE
stop complaining about payment:cryptocurrencies = no (reimport JOSM rules)

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#1013] opened 2020-10-24 15:08 UTC
It is in JOSM group but JOSM r17084 (latest tested) is not complaining about this (for good reason - `payment:cryptocurrencies = yes` would benefit from being more specific but `payment:cryptocurrencies = no ` is enough, there is no need for litany of cryptotags)

Later `payment:debit_cards=yes` is not a complete nonsense, though quite pointless in Poland.

```
{{0.key}}={{0.value}} is inaccurate. Use separate tags for each specific type, e.g. payment:bitcoin=yes or payment:litecoin=yes.
payment:debit_cards=yes is inaccurate. Use separate tags for each specific type, e.g. payment:maestro=yes or payment:girocard=yes.
```

```
node 1740781274 josm iD edit
amenity = vending_machine
brand = KKM
brand:wikidata = Q57515549
name = KKM
opening_hours = 24/7
operator = MPK Kraków
payment:cash = yes
payment:credit_cards = yes
payment:cryptocurrencies = no
```

**Comment by frodrigo** [comment] 2020-10-24 15:53
The update from JOSM is manually and done time to time.
And remove item/class may require extra ma,ual opperation on Osmose frontend.

Please add item/class number or link when reporting issue.

http://osmose.openstreetmap.fr/en/errors/?item=9002&class=9002013

**Comment by matkoniecz** [comment] 2020-10-24 16:14
> Please add item/class number or link when reporting issue.

Sorry!

**Comment by frodrigo** [comment] 2020-11-04 19:28
Is the new state of Osmose for you ? Not sure about it.

**Comment by matkoniecz** [comment] 2020-11-04 19:52
> Is the new state of Osmose for you ?

If it is directed to me then sorry, but I am not understanding the question.

**Comment by frodrigo** [comment] 2020-11-04 19:53
@matkoniecz . Yes. For you, the issue is now fixed ?

**Comment by matkoniecz** [comment] 2020-11-04 20:47
http://osmose.openstreetmap.fr/en/error/36045599-a39e-31e3-f845-8ca2be96a694 - though it seems that problem is caused by something else - by using cryptocurrencies in the title, dropping ", e.g. payment:bitcoin=yes or payment:litecoin=yes." from the title would be best (subtitle already has needed instructions).

But it is Osmose part or is it fully autogenerated from JOSM?

**Comment by frodrigo** [comment] 2020-11-04 20:53
Yes. It generated from JOSM MapCSS validator and Osmose have more field than JOSM.

**Comment by matkoniecz** [comment] 2020-11-04 21:06
What is the source of "e.g. payment:bitcoin=yes or payment:litecoin=yes." title part?

**Comment by frodrigo** [comment] 2020-11-04 21:08
https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/deprecated.mapcss#L714

**Comment by matkoniecz** [comment] 2020-11-04 21:16
Then Osmose is buggy as http://osmose.openstreetmap.fr/en/error/36045599-a39e-31e3-f845-8ca2be96a694 has no `payment:cryptocurrencies=yes` tag


tag | value
-- | -- 
amenity | vending_machine 
name | KKM 
payment:coins | yes 
payment:credit_cards | yes 
payment:debit_cards | yes 
payment:electronic_purses | yes 
payment:notes | yes 
ref | 50 
vending | public_transport_tickets

**Comment by frodrigo** [comment] 2020-11-04 21:20
Yes, the subtitle is right

> payment:electronic_purses=yes is inaccurate. Use separate tags for each specific type, e.g. payment:ep_geldkarte=yes or payment:ep_quick=yes.

But the title not

> {{0.key}}={{0.value}} is inaccurate. Use separate tags for each specific type, e.g. payment:bitcoin=yes or payment:litecoin=yes.

**Comment by frodrigo** [comment] 2020-11-04 21:23
> Yes, the subtitle is right
> 
> > payment:electronic_purses=yes is inaccurate. Use separate tags for each specific type, e.g. payment:ep_geldkarte=yes or payment:ep_quick=yes.
> 
> But the title not
> 
> > {{0.key}}={{0.value}} is inaccurate. Use separate tags for each specific type, e.g. payment:bitcoin=yes or payment:litecoin=yes.

In fact, cannot do better. The title is one of the instance of the subtitle.

Except this, it is ok for you ?

**Comment by matkoniecz** [comment] 2020-11-04 21:30
> Except this, it is ok for you ?

Yes

> The title is one of the instance of the subtitle.

And it is not fixable?

**Comment by frodrigo** [comment] 2020-11-05 09:24
> > The title is one of the instance of the subtitle.
> 
> And it is not fixable?

Not really. We have to put something as title.Nevertheless must be fixed by change on JOSM side using a "group".

**Comment by frodrigo** [comment] 2020-11-05 09:27
FYI @Klumbumbus

**Closed by frodrigo** 2020-11-05 09:27 UTC
Labels: ready
