### ISSUE TITLE
detection of not mapped bicycle infrastructure with mapillary data

### ISSUE THREAD

**Issue by masterofnoroad** [osm-fr/osmose-backend#999] opened 2020-10-10 19:14 UTC
Hello
My idea is to use mapillary traffic sign recognition to find places with missing bicycle infrastructure in osm data. The idea was already implemented in Osmose for different purpose here:

https://lists.openstreetmap.org/pipermail/talk/2017-September/078792.html

It is simple: highlight places on the map that mapillary found traffic sign connected with bicycle and there is no bicycle data on the map.

In Poland we are experiencing boom in new bicycle infrastructure and alot of it stays not maped for long time. Unfortunately im not a programist and dont know how to do this on my own. Mybe someon could pick up this?

**Comment by frodrigo** [comment] 2020-10-10 19:57
What a nice idea!

It does not require code, just a new section in this file: https://github.com/osm-fr/osmose-backend/blob/master/merge_data/mapillary-traffic-signs.mapping.json

Can suggest the new content, please?

**Comment by masterofnoroad** [comment] 2020-10-10 20:50
Those are the traffic signs connected with bicycle infrastructure:

regulatory--bicycles-only--g1
regulatory--dual-path-bicycles-and-pedestrians--g1
regulatory--dual-path-pedestrians-and-bicycles--g1
regulatory--end-of-bicycles-only--g1
regulatory--end-of-dual-path-bicycles-and-pedestrians--g1
regulatory--end-of-dual-path-pedestrians-and-bicycles--g1
regulatory--end-of-mopeds-and-bicycles-only--g1
regulatory--end-of-shared-path-pedestrians-and-bicycles--g1
regulatory--end-of-shared-path-bicycles-and-pedestrians--g1
regulatory--mopeds-and-bicycles-only--g1
regulatory--motorcycles-and-bicycles-only--g1
regulatory--no-bicycles--g1
regulatory--shared-path-pedestrians-and-bicycles--g1
regulatory--shared-path-bicycles-and-pedestrians--g1
information--bicycles-crossing--g3
information--bicycles-crossing--g1
information--trail-crossing--g2

And we need to check for nearby tags:
highway=cycleway
bicycle=designated/yes
cycleway=*

....and then will see how it works :D

**Comment by Famlam** [comment] 2020-10-11 09:21
Something like this I guess? No clue about conflation.
Notes:
 - I know that (at least with the Dutch signs) Mapillary is not good in distinguishing moped and bicycle vs bicycle-only signs, so I didn't split those. 
- I left out the white signs (often g2/g3/g4) as they're pretty similar to the Dutch "[any sign +] except bicycle" signs. Perhaps, if desired, they can be added in a country-specific way. 
- I left out the warning and information signs as they do not necessarily reflect official cycle structures.

```
  {
    "class": 000000000000000,
    "level": 2,
    "otype": [
      "ways"
    ],
    "conflation": 200,
    "title": "cycleway",
    "object": [
      regulatory--bicycles-only--g1,
      regulatory--end-of-bicycles-only--g1,
      regulatory--end-of-bicycles-only--g2,
      regulatory--dual-path-bicycles-and-pedestrians--g1,
      regulatory--end-of-dual-path-bicycles-and-pedestrians--g1,
      regulatory--dual-path-pedestrians-and-bicycles--g1,
      regulatory--end-of-dual-path-pedestrians-and-bicycles--g1,
      regulatory--dual-path-equestrians-and-pedestrians-bicycles--g1,
      regulatory--mopeds-and-bicycles-only--g1,
      regulatory--end-of-mopeds-and-bicycles-only--g1,
      regulatory--shared-path-pedestrians-and-bicycles--g1,
      regulatory--end-of-shared-path-pedestrians-and-bicycles--g1,
      regulatory--shared-path-bicycles-and-pedestrians--g1,
      regulatory--end-of-shared-path-bicycles-and-pedestrians--g1,
      regulatory--motorcycles-and-bicycles-only--g1,
      regulatory--bicycles-and-buses-only--g1
    ],
    "select_tags": [
      {
        "highway": "cycleway"
      },
      {
        "highway": null,
        "bicycle": "designated"
      },
      {
        "highway": null,
        "cycleway": "track"
      },
      {
        "highway": null,
        "cycleway": "opposite_track"
      },
      {
        "highway": null,
        "cycleway:right": "track"
      },
      {
        "highway": null,
        "cycleway:left": "track"
      },
      {
        "highway": null,
        "cycleway:both": "track"
      },
      {
        "highway": null,
        "bicycle_road": "yes"
      },
      {
        "highway": null,
        "cyclestreet": "yes"
      }
    ],
    "generate_tags": {}
  },
```

**Comment by frodrigo** [comment] 2020-10-11 12:53
It looks promising
Please, can you review this results
[Analyser_Merge_Traffic_Signs-switzerland_valais.geojson.zip](https://github.com/osm-fr/osmose-backend/files/5361099/Analyser_Merge_Traffic_Signs-switzerland_valais.geojson.zip)

**Comment by Famlam** [comment] 2020-10-11 18:13
Checked them:
1. OK: [map](https://www.openstreetmap.org/#map=19/46.12174/7.13446) & [image](https://www.mapillary.com/app/?lat=46.121476271076645&lng=7.135077507025548&z=17&pKey=gpOWltzFBo0ehGszTDZlAQ&focus=photo) -> cycleway, not yet drawn on the map
2. OK: [map](https://www.openstreetmap.org/way/136381928#map=19/46.14423/7.04424) & [image](https://www.mapillary.com/app/?lat=46.146066474249295&lng=7.044605950023765&z=14.62860521223548&pKey=AuHXlVrmJfA7ZMwDYs5IUA&focus=photo&x=0.40697549344485634&y=0.5835119342734273&zoom=0.3579751330584327) -> shared foot-and-cycleway with sign => highway=path and/or bicycle=designated expected, footway and bicycle=yes found
3. OK: [map](https://www.openstreetmap.org/#map=19/46.29600/7.91542) & [image](https://www.mapillary.com/app/?lat=46.295996316201155&lng=7.915952253507726&z=17&pKey=BTmymBYD_PZlILXfor_p8w&focus=photo) -> mini mandatory foot/cycleway around bus stop. I wouldn't have drawn such small ways in myself though, but it's technically correct
4. **FAIL**: [map](https://www.openstreetmap.org/way/136381928) & [image](https://www.mapillary.com/app/?lat=46.14470825420376&lng=7.044688074513682&z=17&pKey=DujtlbuxEHZyINKpXFz9zw&focus=photo) -> **Duplicate of nr 2**
5. OK: [map](https://www.openstreetmap.org/way/321124090#map=18/46.22068/7.34487) & [image](https://www.mapillary.com/app/?lat=46.22114743191298&lng=7.346677864823278&z=17&pKey=GQQHJqCQii5DmAhlgtvdhA&focus=photo) -> shared foot/cycleway marked as footway only
6. OK: [map](https://www.openstreetmap.org/way/321124090#map=18/46.22080/7.34532) & [image](https://www.mapillary.com/app/?lat=46.22085477744361&lng=7.345472963157895&z=17&pKey=GaLHBSZgdBT9DrTu1ytmdw&focus=photo) -> (same way, but 100m further; new signs, hence not really a false positive)
7. **FAIL**: [map](https://www.openstreetmap.org/#map=19/46.22558/7.27948) & [image](https://www.mapillary.com/app/?lat=46.22566164894684&lng=7.279341194082235&z=17&pKey=KbN3B50GY2fCd_r05k0J7g&focus=photo&x=0.4183459701056328&y=0.3575776274936732&zoom=0.29814667824356966&signs=true) -> Mapillary false positive in the detection
8. Likely OK: [map](https://www.openstreetmap.org/way/298585492#map=17/46.08802/7.78005) & [image](https://www.mapillary.com/app/?lat=46.08904369997222&lng=7.7795104&z=17&pKey=QLHXX86S6LpxelxIPEw0Dg&focus=photo&x=0.49127477685900606&y=0.6346239182629637&zoom=0) -> shared foot/cycleway marked as highway=track (can't read what's written under the sign). Should be highway=path + bicycle=designated or such.
9. OK: [map](https://www.openstreetmap.org/way/302965154#map=16/46.2207/7.8527) & [image](https://www.mapillary.com/app/?lat=46.223717626452896&lng=7.859107171543087&z=17&pKey=eURU-LLLW6LkjlLzv3ch4Q&focus=photo&x=0.5084834343819447&y=0.5606254356943795&zoom=0) -> foot/cycleway marked as residential road
10. OK: [map](https://www.openstreetmap.org/way/4853464) & [image](https://www.mapillary.com/app/?lat=46.2922858&lng=7.88217039997221&z=17&pKey=k6ek-29rcarQzxOyQTX7mA&focus=photo&x=0.5039679923006408&y=0.3877021739034167&zoom=0) -> Incorrectly tagged cycleway=lane: would be track (or designated on a separate way).
11. OK: [map](https://www.openstreetmap.org/way/293175206) & [image](https://www.mapillary.com/app/?lat=46.2941845&lng=7.903519418127416&z=17&pKey=kubsdieFH0T8GH3jxQe5ZQ&focus=photo&x=0.20218642644424484&y=0.3814023059974915&zoom=1.4850071133851221) -> marked as cycleway=lane rather than cycleway=track
12. OK: [map](https://www.openstreetmap.org/way/802205352#map=17/46.21103/7.83703) & [image](https://www.mapillary.com/app/?lat=46.20860009997222&lng=7.833592199972222&z=17&pKey=mwaA-vk74VuqOte-lComUg&focus=photo&x=0.3480070837837518&y=0.69332366079915&zoom=2.9927754331843337) -> marked as unclassified rather than mandatory way for cyclists


- The false positive in 7 is unavoidable with image detection, and that's what the false positive button is for ;)
- Regarding nr. 2/4 (duplicates of the same traffic sign, same position) : would it help to increase conflation to "merge" them in a single entry? (Or what does conflation mean...?)

**Comment by frodrigo** [comment] 2020-10-11 18:27
Thank you.

>     * Regarding nr. 2/4 (duplicates of the same traffic sign, same position) : would it help to increase conflation to "merge" them in a single entry? (Or what does conflation mean...?)

No, we cannot avoid this. The distance is not a clustering distance but a conflation between Mapillary data and OSM object.

**Comment by Famlam** [comment] 2020-10-12 07:08
Ah, well, I can live with that :). (Having multiple reports of the same object is also the case for the other Mapillary tests)

**Comment by masterofnoroad** [comment] 2020-10-13 16:16
one question:  
it will be integrated with all not mapped max speed limits? or 
it will be possible to filter the results to show only cycle infrastructure?

Im asking because there is so many not mapped speed limits that it will be hard to find the missing bicycle infrastructure spots. The best would be separate entry.

Look at this and try to find missing bicycle infrastructure pin :)

<img width="883" alt="Captura de pantalla 2020-10-13 a las 18 15 31" src="https://user-images.githubusercontent.com/72669347/95887455-256ff000-0d80-11eb-8035-65e886cb130b.png">

**Comment by frodrigo** [comment] 2020-10-13 16:35
Need some code, but can be done.

**Comment by masterofnoroad** [comment] 2020-10-13 17:26
would be worth it, to have good tool...
For me speed limits and bicycle infrastructure are totally separate problems,  they are linked just through sign recognition. And I think cyclists are non really interested in speed limits (I am not as a cyclist  so will not spend my time on it).

**Comment by Famlam** [comment] 2020-10-13 18:08
> would be worth it, to have good tool...

Meanwhile, as soon as the fix is live, http://osmose.openstreetmap.fr/en/errors/?country=netherlands_gelderland&limit=2500&item=8300&level=1%2C2%2C3 might help (of course, select the region of  your interest). Here you can click on the count of the respective issue (rightmost column) to get all of the cycle warnings.

**Comment by frodrigo** [comment] 2020-10-20 11:26
Please review pre-result
http://osmose.openstreetmap.fr/en/errors/?item=8470&level=1%2C2%2C3&useDevItem=all

**Comment by Famlam** [comment] 2020-10-21 09:12
- Checked all of Netherlands_Gelderland -> all OK (either mapillary false detection or incorrectly placed road signs or true missing cycleways)
- Checked a selection of about 25 random picks throughout the world. Mostly OK. Only possibly worrysome one is the US "bicycle lane" sign [(example)](https://www.mapillary.com/app/?focus=photo&pKey=8gbo15gHhcBsiRHSLfw1wQ&signs=true&points=true&lat=61.20872848545637&lng=-149.89143030591774&z=17), which is regulary detected by Mapillary as a cycleway sign, rather than a cycle lane. But it's not that common it seems.
(And they have a lot of mapping to do in Japan, [where the shared foot/cycleway aren't mapped as such](https://www.mapillary.com/app/?focus=photo&pKey=Niimbf12RhZ8_eT2DKm37A&signs=true&points=true&lat=35.64042153096841&lng=139.2729787206&z=17&x=0.1908184232391768&y=0.3854589530239093&zoom=1.988437073765021)).

**Comment by frodrigo** [comment] 2020-10-21 18:32
Publicly enabled.

**Closed by frodrigo** 2020-10-21 18:32 UTC
Labels: enhancement, good first issue, ready

**Comment by YaroShkvorets** [comment] 2020-10-26 00:02
> * Only possibly worrysome one is the US "bicycle lane" sign [(example)](https://www.mapillary.com/app/?focus=photo&pKey=8gbo15gHhcBsiRHSLfw1wQ&signs=true&points=true&lat=61.20872848545637&lng=-149.89143030591774&z=17), which is regulary detected by Mapillary as a cycleway sign, rather than a cycle lane. But it's not that common it seems.

Can confirm that 100% of warnings of this type where I live are false-positives. 
Checked about 30 of those in Ottawa, Canada and every one of them is a bad detection like this. 

![image](https://user-images.githubusercontent.com/29608734/97122516-b6d64f00-16fc-11eb-805f-d148cce292a1.png)

Maybe this sign detection can be turned off for North America?

**Comment by frodrigo** [comment] 2020-10-26 12:21
Yes we can disable the traffic sign for NA, but can also be reported as false positive to Mapillary. But the Osmose -> Mapillary link for false positive is not done.
cc @cbeddow
