### ISSUE TITLE
Sax analyser error after OS update

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#2026] opened 2023-09-12 19:32 UTC
Report of a mail from Tomas Kasparek, owner of an Osmose backend.

I did upgrade of the server OS from debian 11 to 12 and even after solving some problems (missing packages, need to rebuild the pbf reader etc.) I end with SAX error on all countries. May it be related to python upgrade from 3.9 to 3.11 or would you have any other idea where to look?

Interesting part:
```
2023-09-11 10:26:37   Analysing file /home/osmose/work/extracts/austria_niederosterreich.osm.pbf
[32m[INFO] Reading the file/home/osmose/work/extracts/austria_niederosterreich.osm.pbf[0m
2023-09-11 10:26:38   [0;31merror: Fail on <bound method ConditionalRestrictions.node of <plugins.ConditionalRestrictions.ConditionalRestrictions object at 0x7f8e2678da50>> with {'id': 61930579, 'lon': 16.308727400000002, 'lat': 48.23297979999978, 'tag': {'barrier': 'lift_gate', 'bicycle': 'yes', 'foot': 'yes', 'note:vehicle': 'Geschlossen 01.05-31.10', 'source': 'survey 01.2018', 'vehicle:conditional': 'yes @ (Nov-Apr)'}}, {'barrier': 'lift_gate', 'bicycle': 'yes', 'foot': 'yes', 'note:vehicle': 'Geschlossen 01.05-31.10', 'source': 'survey 01.2018', 'vehicle:conditional': 'yes @ (Nov-Apr)'}[0m
2023-09-11 10:26:38   Closing reader and parser
2023-09-11 10:26:39   [0;31merror: error on analyse sax...[0m
2023-09-11 10:26:39     Traceback (most recent call last):
2023-09-11 10:26:39       File "/home/osmose/osmose-backend.git/./osmose_run.py", line 275, in execc
2023-09-11 10:26:39         analyser_obj.analyser()
2023-09-11 10:26:39       File "/home/osmose/osmose-backend.git/analysers/analyser_sax.py", line 69, in analyser
2023-09-11 10:26:39         self._run_analyse()
2023-09-11 10:26:39       File "/home/osmose/osmose-backend.git/analysers/analyser_sax.py", line 491, in _run_analyse
2023-09-11 10:26:39         self.parser.CopyTo(self)
2023-09-11 10:26:39       File "/home/osmose/osmose-backend.git/modules/OsmPbf_libosmbf.py", line 85, in CopyTo
2023-09-11 10:26:39         osm_pbf_parser.read_osm_pbf(self._pbf_file, self)
2023-09-11 10:26:39       File "/home/osmose/osmose-backend.git/modules/OsmPbf_libosmbf.py", line 98, in node
2023-09-11 10:26:39         self._output.NodeCreate(data)
2023-09-11 10:26:39       File "/home/osmose/osmose-backend.git/analysers/analyser_sax.py", line 183, in NodeCreate
2023-09-11 10:26:39         res = meth(data, tags)
2023-09-11 10:26:39               ^^^^^^^^^^^^^^^^
2023-09-11 10:26:39       File "/home/osmose/osmose-backend.git/plugins/ConditionalRestrictions.py", line 265, in node
2023-09-11 10:26:39         return self.way(data, tags, None)
2023-09-11 10:26:39                ^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-09-11 10:26:39       File "/home/osmose/osmose-backend.git/plugins/ConditionalRestrictions.py", line 199, in way
2023-09-11 10:26:39         if not sanitized['isValid']:
2023-09-11 10:26:39                ~~~~~~~~~^^^^^^^^^^^
2023-09-11 10:26:39     TypeError: 'NoneType' object is not subscriptable 
```

**Comment by Famlam** [comment] 2023-09-12 19:38
Did pykopeninghours build well?

**Comment by frodrigo** [comment] 2023-09-12 19:54
I made test with docker and it runs fine.

The docker has the same settings, last debian, python 3.11.

**Comment by Famlam** [comment] 2023-09-12 20:03
I'm pretty sure it must be pykopeninghours. The only reason why it'd be None is if this line is hit:
https://github.com/osm-fr/osmose-backend/blob/dev/plugins/TagFix_Opening_Hours.py#L43
(sanitize_openinghours is a shared function between TagFix_Opening_Hours.py and ConditionalRestrictions.py)

Maybe Tomas can check if there's an importerror? It should be printed already:
https://github.com/osm-fr/osmose-backend/blob/dev/plugins/TagFix_Opening_Hours.py#L29

(Not sure if we should add a check that `sanitized` is not None. I guess it's good to have an error instead of silently failing?)

**Comment by jocelynj** [comment] 2023-09-12 20:08
Could the issue be only with the extract austria_niederosterreich?

**Comment by Famlam** [comment] 2023-09-12 20:46
> Could the issue be only with the extract austria_niederosterreich?

Works in osm110, so it's not an osm data issue.

**Comment by tkas** [comment] 2023-09-13 09:20
OK, can confirm it is related to pykopeninghours. Will check details in logs and code. Thanks for showing the right direction.

**Comment by tkas** [comment] 2023-09-13 10:00
It seems the problem is, that pykopeninghours installs into XXX/site-packages dir, but this is not used by newer python anymore - not in python -c 'import site; print(site.getsitepackages())'. Updated placement by hand now and will see tomorrow - simple import now works. Thanks a lot.

**Comment by tkas** [comment] 2023-09-15 09:02
I can confirm it works now, please @frodrigo could you close this? Thanks everybody for your help.

**Comment by frodrigo** [comment] 2023-09-15 10:39
Good news. Thank you all.

**Closed** 2023-09-15 11:35 UTC

**Comment by jocelynj** [comment] 2023-09-15 17:17
Not sure if it is linked, but when upgrading osm-fr backend to Debian 12, I had to add this in .bashrc for the account running analyses:
```
if [ -f ~/.venvs/backend/bin/activate ]; then
  . ~/.venvs/backend/bin/activate
fi
```
(where pip installs in `~/.venvs/backend/`)
