### ISSUE TITLE
bug with tag addr:street not matching a street name around

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-backend#2342] opened 2024-09-22 11:42 UTC
https://osmose.openstreetmap.fr/en/issue/ccae58df-0725-342d-cfdb-73de746ba44f
item 2060
class 19

https://www.openstreetmap.org/relation/7533821
highway=pedestrian
name=Place Nationale

https://www.openstreetmap.org/node/5777686516
addr:housenumber=5
addr:street=Place Nationale

**Comment by Famlam** [comment] 2024-09-22 12:57
Duplicate of #2050

**Comment by Marc-marc-marc** [comment] 2024-09-23 11:42
2050 is about a MP issue, this one is about a polygon, maybe not the same issue

**Comment by Famlam** [comment] 2024-09-23 13:54
https://www.openstreetmap.org/relation/7533821 is a multipolygon too, what do you mean?

**Comment by Marc-marc-marc** [comment] 2024-09-24 15:27
you are right, sorry

**Closed** 2024-09-24 15:27 UTC
