### ISSUE TITLE
False-positive for tag 'grades'

### ISSUE THREAD

**Issue by iiitomo** [osm-fr/osmose-backend#1569] opened 2022-09-26 07:57 UTC
hi
Osmose currently proposes to change 'grades' into 'grade'.
See screenshot below.
It shouldn't as 'grades' is a valid tag, see https://wiki.openstreetmap.org/wiki/Key:grades

![osmose_error_suggestion_for_grades](https://user-images.githubusercontent.com/58949423/192223581-52b33192-9b9d-4d8e-8cca-cd503e74af36.PNG)

**Comment by frodrigo** [comment] 2022-09-26 08:58
All this suggestions are based on statistics base on territorial data. It may be biased on local tag usage. But yes, keep reporting false positives.

**Comment by Famlam** [comment] 2022-09-26 19:31
This will also be fixed with #1483

**Comment by frodrigo** [comment] 2022-09-26 20:24
`grade` is not a documented tag.

It is proposed because it use in the surrounding. The issue is with the surrounding data. Maybe it should be explained in the popup.

**Comment by frodrigo** [comment] 2022-09-26 20:35
Keep this one open to remind to add more doc in the popup.

**Comment by Famlam** [comment] 2022-10-30 12:15
> Keep this one open to remind to add more doc in the popup.

I hope the suggested change in #1631 matches what you were thinking of?
(Together with the information in the side bar I think it should be clear enough that it's just about counting which tag is more common)

**Closed** 2022-10-30 13:08 UTC
Labels: good first issue, doc
