### ISSUE TITLE
Missed oneway deadend detection

### ISSUE THREAD

**Issue by ComradeRamen** [osm-fr/osmose-backend#2259] opened 2024-07-05 00:56 UTC
1210 class 3 missed https://www.openstreetmap.org/way/629125252/history/13
![image](https://github.com/osm-fr/osmose-backend/assets/150104144/9772604b-154b-42d4-b995-e4da41cae5fe)
It found [motorway_link](https://osmose.openstreetmap.fr/en/issue/e704b919-2b69-0d0e-4741-fab88b795b4b)s in the same area (usa_colorado_denver) that were added after.

**Comment by Famlam** [comment] 2024-07-05 22:36
If I run it locally with just that specific way inverted, I get a warning for node 5940032389, way 629125252
Not sure if there's an easy way to run it on the state between Jul 2, 19:07 and Jul 5, 1:10. Do you have another example by any chance which is still live?

> It found [motorway_link](https://osmose.openstreetmap.fr/en/issue/e704b919-2b69-0d0e-4741-fab88b795b4b)s in the same area (usa_colorado_denver) that were added after.

As this link will disappear as soon as the analyser runs again: [this node](https://www.openstreetmap.org/node/5753109918), [this way](https://www.openstreetmap.org/way/606853345). The bad modification was made Jul 2, 18:27
(So there is also the chance that the data was obtained from the server in that 40 minute interval)

**Comment by ComradeRamen** [comment] 2024-07-06 23:18
> Do you have another example by any chance which is still live?

This was the only miss I found.

**Comment by Famlam** [comment] 2024-07-26 09:29
I'm afraid that there's very little we can do if it is not reproducible.
Especially since it may just have been a matter of unlucky timing (those 40 minutes I mentioned). I hope you don't mind that I'll close this until there's a live example?

**Closed by Famlam** 2024-07-26 09:29 UTC
