### ISSUE TITLE
{0}={0}

### ISSUE THREAD

**Issue by maro-21** [osm-fr/osmose-backend#914] opened 2020-06-20 12:51 UTC
I think such texts `{0.key}={0.value} with {1.key}={1.value}` full of variables shouldn't be in the GUI. These are the titles of some issues. Subtitles are correct and they are replaced by respect values.
- [ ] 2080 highway: 20805 -> {0.key}={0.value} without highway=footway|construction
- [ ] 3032 multiple tags: 30328, 30329 -> {0.key}={0.value} with {1.key}={1.value}
- [ ] disused 4010: 40101 {2.key}={2.value} is preferred to {1.key}={1.value} http://osmose.openstreetmap.fr/en/errors/?source=14338&item=4010&class=40101
- [ ] incompatible tags: 40301 http://osmose.openstreetmap.fr/en/errors/?item=4030&class=40301
- [ ] contruction: Inconsistent tagging of {1.key} http://osmose.openstreetmap.fr/en/errors/?item=4070&class=40701
- [x] erroneous boundary 6060: class 1: Hole between administrative boundaries of admin_level %s, http://osmose.openstreetmap.fr/en/errors/?item=6060&class=1
- [ ] addresses 9000: http://osmose.openstreetmap.fr/en/errors/?item=9000
	9000003 	Same value of {0.key} and {1.key}
	9000004 	{0.key} without number
- [ ] combinations 9001
	{0.key} on a relation without {1.key}={1.value} http://osmose.openstreetmap.fr/en/errors/?item=9001&class=9001003
	incomplete usage of {0.key} on a way without {1.key} http://osmose.openstreetmap.fr/en/errors/?item=9001&class=9001004
- and a lot of JOSM validator issues.

There should be general text instead of repeating the same in title and subtitle.

**Comment by frodrigo** [comment] 2020-06-20 14:44
It is a limitation of usage of JOSM MapCSS in Osmose.
The title is a static string, but this map nothing of MapCSS, so use the group when exits, else uses the message before replacement of placeholder.

But the MapCSS from Osmose can be improved, by adding group, event where is nothing to group. Other solution is to add support Osmose specific new property "title".

FYI @Klumbumbus

**Comment by frodrigo** [comment] 2020-07-13 20:04
Maybe we can add the title of the MapCSS file, but it is very generic.

**Comment by maro-21** [comment] 2020-10-14 20:21
Was it fixed?

**Comment by frodrigo** [comment] 2020-10-14 20:25
The issue is inherent the usage of JOSM MapCSS in Osmose. The MapCSS should be "improved" on JOSM side by changing text or using groups. But is not really make sens for JOSM to do this.

**Comment by maro-21** [comment] 2020-10-14 20:33
I didn't understand.
The issue is on the Osmose side.
Does e.g. "2080 highway: 20805 -> {0.key}={0.value} without highway=footway|construction" come from JOSM?

**Comment by frodrigo** [comment] 2020-10-14 20:38
Yes, the ones of https://github.com/osm-fr/osmose-backend/blob/master/plugins/Bicycle.validator.mapcss can be fixed on Osmose side.

**Closed** 2020-10-20 17:47 UTC
Labels: enhancement, question, ready
