### ISSUE TITLE
Fixed items appear as errors again several weeks after fixing them

### ISSUE THREAD

**Issue by nobohan** [osm-fr/osmose-backend#193] opened 2017-04-03 10:23 UTC
Hi, 

I regularly use osmose to watch potential errors and fix them around my place. I noticed several times that some errors that I fixed a few weeks ago suddenly showed up again on the webmap, a few weeks after I fixed them. Of course, I have checked the OSM data and the error is still fixed.  

It happened again this morning! Here's the information on the reported error: [http://osmose.openstreetmap.fr/en/error/11276422321](http://osmose.openstreetmap.fr/en/error/11276422321)

And the node that was causing the error was deleted 6 months ago (fyi, the info about the church was redundant with the church polygon): [http://www.openstreetmap.org/node/2622695730](http://www.openstreetmap.org/node/2622695730)

Is it a bug or something I don't understand? 
Julien

**Comment by frodrigo** [comment] 2017-04-08 12:12
Hum. It's gone again. It's not the first time we have issue like this one.
@jocelynj any idea ? maybe old extract are used on some backend ? Btw, with the upcomming new timestamps calculation method we can reject update with old data.

**Comment by nobohan** [comment] 2017-04-08 17:18
Euh the error is gone according to the previous link but it still appears in the osmose map, under this new id: [http://osmose.openstreetmap.fr/en/error/11371239906](http://osmose.openstreetmap.fr/en/error/11371239906)

BTW, it is not the only case I found: there are also these errors reported that I corrected some months ago: http://osmose.openstreetmap.fr/en/error/11371251761 & http://osmose.openstreetmap.fr/en/error/11371251762

So it seems the id of the error change from times to times. Maybe it helps...

Julien

**Comment by frodrigo** [comment] 2017-05-02 20:14
Can you give us item number corresponding to this issue. Because at this time, I have no idea about what we are talking about.

**Comment by nobohan** [comment] 2017-05-02 20:29
It is still there: http://osmose.openstreetmap.fr/en/error/11775724301
and here: http://osmose.openstreetmap.fr/en/error/11775742819

**Comment by frodrigo** [comment] 2017-05-02 20:45
There gone again. Please does not mark them as fixed or false positives.
I need the item and class fields of this kind of issue to know where there are coming from.

**Comment by frodrigo** [comment] 2017-05-02 20:46
ok 
```
marker.item 	3032
marker.source 	3763
marker.class 	3032
marker.elems 	node2622695730
marker.subclass 	1 
```

```
marker.item 	5010
marker.source 	3763
marker.class 	903
marker.elems 	way321070334
marker.subclass 	1 
```

**Comment by frodrigo** [comment] 2017-05-02 21:10
@jocelynj it raises issues on old data
Node 2622695730 is delete from months.
country=belgium_wallonia_french_community
timestamp=2017-05-02 00:40:45 (but I doest not kown if it's the old or new way to compute it)

**Comment by frodrigo** [comment] 2017-05-02 21:17
```
./osmconvert --out-statistics ../extracts/wallonia_french_community-latest.osm.pbf 
timestamp min: 2005-07-23T02:49:39Z
timestamp max: 2017-05-02T00:40:45Z
```
```
./osmconvert ../extracts/wallonia_french_community-latest.osm.pbf | grep 2622695730
        <node id="2622695730" lat="49.7166784" lon="5.5602828" version="2" timestamp="2014-12-08T05:59:54Z" changeset="27326787" uid="2419327" user="Franc9876">
```
The extract is in a compromised state.
The node is now delete in version 3.
http://www.openstreetmap.org/node/2622695730

**Comment by jocelynj** [comment] 2017-06-29 21:43
It should hopefully be fixed by b293e0d94264be7720a0fc3ea19ddc8312ab40ae.

**Comment by jocelynj** [comment] 2017-06-29 21:47
Sorry, I shouldn't have closed this bug - the issue is still present on extract from download.openstreetmap.fr.

**Comment by frodrigo** [comment] 2018-08-15 11:45
It seam ok for now.
The extract should be ok, an the frontend is now protected from uploading old data.

**Closed by frodrigo** 2018-08-15 11:45 UTC
Labels: osm-data
