### ISSUE TITLE
Should construction ways be valid connections?

### ISSUE THREAD

**Issue by ComradeRamen** [osm-fr/osmose-backend#2170] opened 2024-03-18 02:11 UTC
Item: 1210
Class: 2
I'm not sure if this was intended but class 2 doesn't count construction ways as valid connections. Relevant [commit](https://github.com/osm-fr/osmose-backend/commit/7aad0c7cf86a274a50669776f24fe3cdb6446736) 

Most of the motorways detected in class 2 are connected to construction ways.

**Comment by Famlam** [comment] 2024-03-18 08:25
I personally agree with you due to the usually temporary nature of construction roads, see also my argumentation here https://github.com/osm-fr/osmose-backend/issues/1523#issuecomment-1226161725 and #1420 

Closing as a duplicate of the latter

**Closed by Famlam** 2024-03-18 08:25 UTC

**Comment by ComradeRamen** [comment] 2024-03-18 09:28
Sorry about the duplicate. I'll have a PR as soon as everything else is merged
