### ISSUE TITLE
item 8110 - Public service not integrated : to fix with deprecated tag 

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osmose-backend#293] opened 2018-04-30 16:05 UTC
source | 2300
item | 8110
class | 11
title | en | Public service not integrated
subtitle | fr | Caisse d'allocations familiales
...
tags_create | office | administrative

Moreover, no "fix-edit"

HTH

**Comment by frodrigo** [comment] 2018-04-30 16:10
Duplicate of #236 ?

**Comment by deuzeffe** [comment] 2018-04-30 17:11
Yes.

**Comment by frodrigo** [comment] 2018-04-30 18:12
Please, can you help on the first issue.

**Closed by frodrigo** 2018-04-30 18:12 UTC

**Comment by deuzeffe** [comment] 2018-04-30 20:26
@frodrigo like this https://github.com/osm-fr/osmose-backend/issues/236#issuecomment-385467249 ?
