### ISSUE TITLE
ProgrammingError: more than one row returned by a subquery used as an expression

### ISSUE THREAD

**Issue by stephankn** [osm-fr/osmose-backend#453] opened 2019-02-20 22:36 UTC
v1.1-2019-02-16-40-g721f9d76

multiple countries affected by SQL error:

```
2019-02-20 06:17:10 china_fujian : osmosis_highway_deadend
2019-02-20 06:17:10   run osmosis all analyser Analyser_Osmosis_Highway_DeadEnd
2019-02-20 06:17:10   analyser_osmosis_highway_deadend.py:187 sql
2019-02-20 06:17:14   analyser_osmosis_highway_deadend.py:188 sql
2019-02-20 06:17:14   analyser_osmosis_highway_deadend.py:189 sql
2019-02-20 06:17:15   analyser_osmosis_highway_deadend.py:190 sql
2019-02-20 06:17:25   analyser_osmosis_highway_deadend.py:191 sql
2019-02-20 06:17:44   analyser_osmosis_highway_deadend.py:192 xml generation
2019-02-20 06:17:44   error: sql=
SELECT
  DISTINCT ON (oneway.id)
  oneway.id,
  oneway.nid,
  (SELECT ST_AsText(geom) FROM nodes WHERE id = oneway.nid)
FROM
  oneway
  LEFT JOIN r ON
    r.nid = oneway.nid
WHERE
  r.nid IS NULL

2019-02-20 06:17:44   error: error on analyse osmosis_highway_deadend...
2019-02-20 06:17:44     Traceback (most recent call last):
2019-02-20 06:17:44       File "./osmose_run.py", line 229, in execc
2019-02-20 06:17:44         analyser_obj.analyser()
2019-02-20 06:17:44       File "/opt/osmose-backend/analysers/Analyser_Osmosis.py", line 183, in analyser
2019-02-20 06:17:44         self.analyser_osmosis_common()
2019-02-20 06:17:44       File "/opt/osmose-backend/analysers/analyser_osmosis_highway_deadend.py", line 192, in analyser_osmosis_common
2019-02-20 06:17:44         self.run(sql35, lambda res: {"class":3, "data":[self.way_full, self.node, self.positionAsText]})
2019-02-20 06:17:44       File "/opt/osmose-backend/analysers/Analyser_Osmosis.py", line 441, in run
2019-02-20 06:17:44         self.run0(sql, callback_package)
2019-02-20 06:17:44       File "/opt/osmose-backend/analysers/Analyser_Osmosis.py", line 398, in run0
2019-02-20 06:17:44         self.giscurs.execute(sql)
2019-02-20 06:17:44       File "/usr/local/lib/python2.7/site-packages/psycopg2/extras.py", line 141, in execute
2019-02-20 06:17:44         return super(DictCursor, self).execute(query, vars)
2019-02-20 06:17:44     ProgrammingError: more than one row returned by a subquery used as an expression
2019-02-20 06:17:44
```

**Comment by frodrigo** [comment] 2019-02-20 23:11
```
(SELECT ST_AsText(geom) FROM nodes WHERE id = oneway.nid)
```
```
ProgrammingError: more than one row returned by a subquery used as an expression
```
This one is very strange.

**Comment by stephankn** [comment] 2019-02-21 06:17
Is there any race condition involved? It would fail if we have duplicate id in table nodes, right? Could something be fishy with the import of data?

This morning it did run fine:
```
2019-02-21 05:58:07 china_fujian : osmosis_highway_deadend
2019-02-21 05:58:07   run osmosis all analyser Analyser_Osmosis_Highway_DeadEnd
2019-02-21 05:58:07   analyser_osmosis_highway_deadend.py:187 sql
2019-02-21 05:58:08   analyser_osmosis_highway_deadend.py:188 sql
2019-02-21 05:58:08   analyser_osmosis_highway_deadend.py:189 sql
2019-02-21 05:58:08   analyser_osmosis_highway_deadend.py:190 sql
2019-02-21 05:58:10   analyser_osmosis_highway_deadend.py:191 sql
2019-02-21 05:58:11   analyser_osmosis_highway_deadend.py:192 xml generation
2019-02-21 05:58:12   analyser_osmosis_highway_deadend.py:195 xml generation
2019-02-21 05:58:14   update
2019-02-21 05:58:14     iteration=1
2019-02-21 05:58:15     OK
```

yesterday I also had this one in `20190220_122306-indonesia_central_sulawesi.log`

We have an updated osmosis since a few days. This might surface some race conditions we did not see before.

**Comment by frodrigo** [comment] 2019-02-21 12:14
Yes . maybe linked to the update of Osmosis.

I can't reproduce this one today.

**Comment by stephankn** [comment] 2019-02-21 20:04
I grepp'ed all logs from 2019. These SQL issues started to pop up first on the 17th, this was the day after osmosis was updated. Could the input data have issues leading to some broken import with the newer version? As I don't cache data a new extract might change the situation. I could try to fetch pbf files once a problem was reported and see whether it can be then reproduced...

Here are the logs:
```
20190217_040341-india_gujarat.log:2019-02-17 03:07:28     ProgrammingError: column "nodes.geom" must appear in the GROUP BY clause or be used in an aggregate function
20190217_040359-india_haryana.log:2019-02-17 03:08:39     ProgrammingError: column "nodes.geom" must appear in the GROUP BY clause or be used in an aggregate function
20190217_040359-india_haryana.log:2019-02-17 03:08:39     ProgrammingError: function relation_locate(bigint) does not exist
20190217_040359-india_haryana.log:2019-02-17 03:08:39     ProgrammingError: function relation_locate(bigint) does not exist
20190217_040359-india_haryana.log:2019-02-17 03:08:39     ProgrammingError: function relation_locate(bigint) does not exist
20190217_040359-india_haryana.log:2019-02-17 03:08:40     ProgrammingError: function relation_locate(bigint) does not exist
20190217_040359-india_haryana.log:2019-02-17 03:08:42     ProgrammingError: function relation_locate(bigint) does not exist
20190217_040359-india_haryana.log:2019-02-17 03:08:42     ProgrammingError: function relation_locate(bigint) does not exist
20190217_040359-india_haryana.log:2019-02-17 03:09:06     ProgrammingError: function any_locate(character, bigint) does not exist
20190217_040359-india_haryana.log:2019-02-17 03:09:06     ProgrammingError: function relation_locate(bigint) does not exist
20190217_040359-india_haryana.log:2019-02-17 03:09:07     ProgrammingError: function any_locate(text, bigint) does not exist
20190217_040745-india_jammu_and_kashmir.log:2019-02-17 03:10:25     ProgrammingError: function way_locate(geometry) does not exist
20190217_040927-india_jharkhand.log:2019-02-17 03:10:28     ProgrammingError: relation "metainfo" does not exist
20190217_040927-india_jharkhand.log:2019-02-17 03:10:31     ProgrammingError: function way_locate(geometry) does not exist
20190217_041051-india_madhya_pradesh.log:2019-02-17 05:37:49     ProgrammingError: more than one row returned by a subquery used as an expression
20190217_041051-india_madhya_pradesh.log:2019-02-17 06:13:29     ProgrammingError: relation "metainfo" does not exist
20190217_041105-india_madhya_pradesh.log:2019-02-17 05:37:49     ProgrammingError: more than one row returned by a subquery used as an expression
20190217_041105-india_maharashtra.log:2019-02-17 03:38:50     ProgrammingError: relation "metainfo" does not exist
20190217_041105-india_maharashtra.log:2019-02-17 03:38:50     ProgrammingError: relation "metainfo" does not exist
20190217_041105-india_maharashtra.log:2019-02-17 03:38:50     ProgrammingError: relation "metainfo" does not exist
20190217_044317-india_national_capital_territory_of_delhi.log:2019-02-17 03:46:13     ProgrammingError: function way_locate(geometry) does not exist
20190217_044716-india_punjab.log:2019-02-17 03:53:45     ProgrammingError: function way_locate(geometry) does not exist
20190217_045502-india_tamil_nadu.log:2019-02-17 04:12:51     ProgrammingError: function way_locate(geometry) does not exist
20190217_070247-china_gansu.log:2019-02-17 06:10:01     ProgrammingError: function way_locate(geometry) does not exist
20190217_071331-china_guizhou.log:2019-02-17 06:15:47     ProgrammingError: function way_locate(geometry) does not exist
20190217_071442-china_hainan.log:2019-02-17 06:16:03     ProgrammingError: relation "metainfo" does not exist
20190217_071557-china_hebei.log:2019-02-17 21:10:49     ProgrammingError: more than one row returned by a subquery used as an expression
20190217_071557-china_hebei.log:2019-02-17 21:21:41     ProgrammingError: more than one row returned by a subquery used as an expression
20190217_071557-china_hebei.log:2019-02-17 22:27:14     ProgrammingError: relation "metainfo" does not exist
20190217_071612-china_hebei.log:2019-02-17 21:10:26     ProgrammingError: more than one row returned by a subquery used as an expression
20190217_071612-china_hebei.log:2019-02-17 21:21:21     ProgrammingError: more than one row returned by a subquery used as an expression
20190217_111617-indonesia_banten.log:2019-02-17 10:40:38     ProgrammingError: function way_locate(geometry) does not exist
20190217_114052-indonesia_central_java.log:2019-02-17 10:52:22     ProgrammingError: column "nodes.geom" must appear in the GROUP BY clause or be used in an aggregate function
20190217_145648-indonesia_west_java.log:2019-02-17 15:14:41     ProgrammingError: relation "metainfo" does not exist
20190217_145648-indonesia_west_java.log:2019-02-17 15:14:41     ProgrammingError: relation "metainfo" does not exist
20190217_145648-indonesia_west_java.log:2019-02-17 15:14:41     ProgrammingError: relation "metainfo" does not exist
20190217_145648-indonesia_west_java.log:2019-02-17 15:14:46     ProgrammingError: function way_locate(geometry) does not exist
20190217_163851-indonesia_yogyakarta.log:2019-02-17 15:47:23     ProgrammingError: function way_locate(geometry) does not exist
20190220_051434-india_punjab.log:2019-02-20 04:17:42     ProgrammingError: relation "metainfo" does not exist
20190220_051434-india_punjab.log:2019-02-20 04:17:46     ProgrammingError: function way_locate(geometry) does not exist
20190220_051514-india_rajasthan.log:2019-02-20 04:18:52     ProgrammingError: function way_locate(geometry) does not exist
20190220_051856-india_tamil_nadu.log:2019-02-20 04:26:56     ProgrammingError: column "nodes.geom" must appear in the GROUP BY clause or be used in an aggregate function
20190220_051905-india_telangana.log:2019-02-20 04:29:08     ProgrammingError: column "nodes.geom" must appear in the GROUP BY clause or be used in an aggregate function
20190220_052726-india_uttar_pradesh.log:2019-02-20 04:32:08     ProgrammingError: column "nodes.geom" must appear in the GROUP BY clause or be used in an aggregate function
20190220_052726-india_uttar_pradesh.log:2019-02-20 04:32:09     ProgrammingError: function relation_locate(bigint) does not exist
20190220_052726-india_uttar_pradesh.log:2019-02-20 04:32:09     ProgrammingError: function relation_locate(bigint) does not exist
20190220_052726-india_uttar_pradesh.log:2019-02-20 04:32:09     ProgrammingError: function relation_locate(bigint) does not exist
20190220_052726-india_uttar_pradesh.log:2019-02-20 04:32:10     ProgrammingError: function relation_locate(bigint) does not exist
20190220_052726-india_uttar_pradesh.log:2019-02-20 04:32:11     ProgrammingError: function relation_locate(bigint) does not exist
20190220_052726-india_uttar_pradesh.log:2019-02-20 04:32:12     ProgrammingError: function relation_locate(bigint) does not exist
20190220_052726-india_uttar_pradesh.log:2019-02-20 04:32:17     ProgrammingError: function any_locate(character, bigint) does not exist
20190220_052726-india_uttar_pradesh.log:2019-02-20 04:32:17     ProgrammingError: function relation_locate(bigint) does not exist
20190220_052726-india_uttar_pradesh.log:2019-02-20 04:32:18     ProgrammingError: function any_locate(text, bigint) does not exist
20190220_053108-india_west_bengal.log:2019-02-20 04:39:11     ProgrammingError: column "nodes.geom" must appear in the GROUP BY clause or be used in an aggregate function
20190220_053108-india_west_bengal.log:2019-02-20 04:39:12     ProgrammingError: function relation_locate(bigint) does not exist
20190220_053108-india_west_bengal.log:2019-02-20 04:39:14     ProgrammingError: function relation_locate(bigint) does not exist
20190220_053108-india_west_bengal.log:2019-02-20 04:39:14     ProgrammingError: function relation_locate(bigint) does not exist
20190220_053108-india_west_bengal.log:2019-02-20 04:39:16     ProgrammingError: function relation_locate(bigint) does not exist
20190220_053108-india_west_bengal.log:2019-02-20 04:39:30     ProgrammingError: function relation_locate(bigint) does not exist
20190220_053108-india_west_bengal.log:2019-02-20 04:39:33     ProgrammingError: function relation_locate(bigint) does not exist
20190220_053108-india_west_bengal.log:2019-02-20 04:43:57     ProgrammingError: relation "metainfo" does not exist
20190220_053108-india_west_bengal.log:2019-02-20 04:43:58     ProgrammingError: relation "metainfo" does not exist
20190220_053108-india_west_bengal.log:2019-02-20 04:43:58     ProgrammingError: relation "metainfo" does not exist
20190220_053108-india_west_bengal.log:2019-02-20 04:43:59     ProgrammingError: relation "metainfo" does not exist
20190220_053108-india_west_bengal.log:2019-02-20 04:43:59     ProgrammingError: relation "metainfo" does not exist
20190220_053108-india_west_bengal.log:2019-02-20 04:44:00     ProgrammingError: relation "metainfo" does not exist
20190220_053108-india_west_bengal.log:2019-02-20 04:44:00     ProgrammingError: relation "metainfo" does not exist
20190220_053108-india_west_bengal.log:2019-02-20 04:44:01     ProgrammingError: relation "metainfo" does not exist
20190220_053108-india_west_bengal.log:2019-02-20 04:44:01     ProgrammingError: relation "metainfo" does not exist
20190220_053108-india_west_bengal.log:2019-02-20 04:44:01     ProgrammingError: relation "metainfo" does not exist
20190220_053108-india_west_bengal.log:2019-02-20 04:44:02     ProgrammingError: relation "metainfo" does not exist
20190220_053108-india_west_bengal.log:2019-02-20 04:44:02     ProgrammingError: relation "metainfo" does not exist
20190220_053108-india_west_bengal.log:2019-02-20 04:44:03     ProgrammingError: relation "metainfo" does not exist
20190220_053108-india_west_bengal.log:2019-02-20 04:44:03     ProgrammingError: relation "metainfo" does not exist
20190220_053108-india_west_bengal.log:2019-02-20 04:44:03     ProgrammingError: relation "metainfo" does not exist
20190220_053108-india_west_bengal.log:2019-02-20 04:44:04     ProgrammingError: relation "metainfo" does not exist
20190220_053254-taiwan.log:2019-02-20 04:51:45     ProgrammingError: column "nodes.geom" must appear in the GROUP BY clause or be used in an aggregate function
20190220_053254-taiwan.log:2019-02-20 04:51:47     ProgrammingError: function relation_locate(bigint) does not exist
20190220_053254-taiwan.log:2019-02-20 04:51:50     ProgrammingError: function relation_locate(bigint) does not exist
20190220_053254-taiwan.log:2019-02-20 04:51:50     ProgrammingError: function relation_locate(bigint) does not exist
20190220_053254-taiwan.log:2019-02-20 04:51:54     ProgrammingError: function relation_locate(bigint) does not exist
20190220_053254-taiwan.log:2019-02-20 04:52:01     ProgrammingError: function relation_locate(bigint) does not exist
20190220_053254-taiwan.log:2019-02-20 04:52:06     ProgrammingError: function relation_locate(bigint) does not exist
20190220_053254-taiwan.log:2019-02-20 04:56:16     ProgrammingError: relation "metainfo" does not exist
20190220_053254-taiwan.log:2019-02-20 04:56:19     ProgrammingError: relation "metainfo" does not exist
20190220_055025-china_chongqing.log:2019-02-20 04:56:45     ProgrammingError: relation "metainfo" does not exist
20190220_055025-china_chongqing.log:2019-02-20 04:56:45     ProgrammingError: relation "metainfo" does not exist
20190220_055025-china_chongqing.log:2019-02-20 04:56:53     ProgrammingError: function way_locate(geometry) does not exist
20190220_055637-china_fujian.log:2019-02-20 06:10:45     ProgrammingError: column "nodes.geom" must appear in the GROUP BY clause or be used in an aggregate function
20190220_055637-china_fujian.log:2019-02-20 06:17:44     ProgrammingError: more than one row returned by a subquery used as an expression
20190220_055658-china_fujian.log:2019-02-20 06:11:16     ProgrammingError: column "nodes.geom" must appear in the GROUP BY clause or be used in an aggregate function
20190220_055658-china_fujian.log:2019-02-20 06:17:49     ProgrammingError: more than one row returned by a subquery used as an expression
20190220_055658-china_gansu.log:2019-02-20 05:03:44     ProgrammingError: relation "metainfo" does not exist
20190220_055658-china_gansu.log:2019-02-20 05:03:55     ProgrammingError: function way_locate(geometry) does not exist
20190220_114728-indonesia_central_java.log:2019-02-20 11:22:52     ProgrammingError: function way_locate(geometry) does not exist
20190220_122306-indonesia_central_sulawesi.log:2019-02-20 11:52:20     ProgrammingError: more than one row returned by a subquery used as an expression
20190220_122306-indonesia_central_sulawesi.log:2019-02-20 12:17:11     ProgrammingError: relation "metainfo" does not exist
20190220_164111-indonesia_west_java.log:2019-02-20 17:12:06     ProgrammingError: function way_locate(geometry) does not exist
20190220_181212-indonesia_west_nusa_tenggara.log:2019-02-20 17:35:15     ProgrammingError: relation "metainfo" does not exist
20190220_183850-indonesia_yogyakarta.log:2019-02-20 17:47:26     ProgrammingError: relation "metainfo" does not exist
20190220_183850-indonesia_yogyakarta.log:2019-02-20 17:47:30     ProgrammingError: function way_locate(geometry) does not exist
```

**Comment by stephankn** [comment] 2019-02-21 20:07
Not certain whether the SQL should be made more robust. Maybe duplicating the other occurrences to this one?

**Comment by frodrigo** [comment] 2019-02-21 20:11
```
ProgrammingError: relation "metainfo" does not exist
```
Can you check the log around the Osmosis import. It's look like the import was not fully done.

**Comment by stephankn** [comment] 2019-02-22 06:20
I have added a full log which contains multiple issues.

Osmosis import looks OK, at least no obvious problem reported.

Do you think we can log some debug stuff around the import process? For example name, size, timestamp, SHA-1 hash of the file we are going to import. And later the number of nodes/ways/relations in the database?

[20190220_053254-taiwan.log](https://github.com/osm-fr/osmose-backend/files/2892639/20190220_053254-taiwan.log)

**Comment by frodrigo** [comment] 2019-02-22 17:00
It was only once, or your still have this kind of issues ?

**Comment by stephankn** [comment] 2019-02-22 17:18
It happened for a few countries on the 17th, and for a few more countries on the 20th. It was not observed before the 17th and not on the days after (21st/22nd).

**Comment by frodrigo** [comment] 2019-02-27 07:30
Can I close this set of issues?

**Comment by stephankn** [comment] 2019-02-27 15:19
I closed others from the set. Not certain what triggered it sporadically. With the docker image always reset there are not so many changing parts.
Probably #452 also belongs to this category.

Maybe adding some extra logs to know more in case it appears again helps.

**Comment by frodrigo** [comment] 2019-03-09 19:26
I just review the taiwan.log and clearly the OSM data import fails. It contains too few steps.

```
2019-02-20 04:33:05 [0;31mimport osmosis data[0m
2019-02-20 04:33:05   Feb 20, 2019 4:33:05 AM org.openstreetmap.osmosis.core.Osmosis run
2019-02-20 04:33:05   INFO: Osmosis Version 0.47
2019-02-20 04:33:05   Feb 20, 2019 4:33:05 AM org.openstreetmap.osmosis.core.Osmosis run
2019-02-20 04:33:05   INFO: Preparing pipeline.
2019-02-20 04:33:05   Feb 20, 2019 4:33:05 AM org.openstreetmap.osmosis.core.Osmosis run
2019-02-20 04:33:05   INFO: Launching pipeline execution.
2019-02-20 04:33:05   Feb 20, 2019 4:33:05 AM org.openstreetmap.osmosis.core.Osmosis run
2019-02-20 04:33:05   INFO: Pipeline executing, waiting for completion.
2019-02-20 04:34:26   Feb 20, 2019 4:34:26 AM org.openstreetmap.osmosis.core.Osmosis run
2019-02-20 04:34:26   INFO: Pipeline complete.
2019-02-20 04:34:26   Feb 20, 2019 4:34:26 AM org.openstreetmap.osmosis.core.Osmosis run
2019-02-20 04:34:26   INFO: Total execution time: 81758 milliseconds.
2019-02-20 04:34:27    SET
2019-02-20 04:34:27    COPY 1
2019-02-20 04:34:27    ALTER TABLE
2019-02-20 04:34:27    DROP INDEX
2019-02-20 04:34:41    COPY 7448292
2019-02-20 04:34:47    ALTER TABLE
2019-02-20 04:36:19    CREATE INDEX
2019-02-20 04:36:19    CREATE FUNCTION
2019-02-20 04:36:19    DROP TRIGGER
2019-02-20 04:36:19    DROP TRIGGER
2019-02-20 04:36:19 [0;31mimport osmosis post scripts[0m
2019-02-20 04:36:19    CREATE FUNCTION
2019-02-20 04:36:19    CREATE FUNCTION
2019-02-20 04:36:19    CREATE FUNCTION
2019-02-20 04:36:19    CREATE FUNCTION
2019-02-20 04:36:19 [0;31minit osmosis replication for diff[0m
```

**Comment by frodrigo** [comment] 2019-03-09 19:39
The taiwan.log only import 1 user from OSM file (`COPY 1`), this is suspect. I seem it's hang up on `osmosis / ImportDatabase.sql` at` CREATE INDEX idx_nodes_geom ON nodes USING gist (geom); `step.

Do you run multiple Osmose runs at same, time? Are you sure there is always enough free space or memory?

Can you look at other fails logs to see it it's always the same pattern?
Correct pattern should look this this:
```
2019-03-09 11:30:33    SET
2019-03-09 11:30:34    COPY 5377
2019-03-09 11:30:35    ALTER TABLE
2019-03-09 11:30:36    DROP INDEX
2019-03-09 11:31:07    COPY 10383517
2019-03-09 11:31:16    ALTER TABLE
2019-03-09 11:33:41    CREATE INDEX
2019-03-09 11:33:41    ALTER TABLE
2019-03-09 11:33:41    ANALYZE
```

I don't know why there is no error message from SQL fails.

**Comment by stephankn** [comment] 2019-03-11 13:20
With docker-compose managing a unique instance I am quite certain that only one osmose runs at a time. But in this specific time something certainly broke and was not detected as a problem, as there had been a dangling network setup in docker for some countries. Not all involved here, but certainly there exists a code-path in which something can go horribly wrong and is not detected as an error.

**Closed** 2019-05-05 12:48 UTC
