### ISSUE TITLE
Escalators mis-flagged as inaccessible one-way streets

### ISSUE THREAD

**Issue by brawer** [osm-fr/osmose-backend#1637] opened 2022-11-04 07:50 UTC
Osmose currently flags escalators and stairs as “One way inaccessible or missing parking or parking entrance”, ie. one-way paths that are disconnected from the road network. For example in [Zürich Airport](https://osmose.openstreetmap.fr/en/map/#zoom=16&lat=47.45246&lon=8.56063&item=0001%2C1010%2C1060%2C1070%2C1100%2C1140%2C1150%2C1180%2C1190%2C1200%2C1210%2C1220%2C1221%2C1240%2C1250%2C1260%2C1280%2C1290&level=1) or [Charles de Gaulle Airport](https://osmose.openstreetmap.fr/en/map/#zoom=17&lat=49.014824&lon=2.541956&item=0001%2C1010%2C1060%2C1070%2C1100%2C1140%2C1150%2C1180%2C1190%2C1200%2C1210%2C1220%2C1221%2C1240%2C1250%2C1260%2C1280%2C1290&level=1&issue_uuid=484fdd2b-3ed3-b957-6756-f642d2482f16).

Should this Osmose check be disabled for escalators and stairs? Or does it indeed indicate a data problem? After all, in the real world, people can reach the interior of a building through the entrance, so the indoor walking network probably *should* be connected to the outside somehow. So perhaps the Osmose check is actually correct, and this is more a user interface problem? In that case, perhaps the displayed message should be made less confusing?

**Comment by frodrigo** [comment] 2022-11-04 10:43
I think there is a mapping issue on OSM data.

Eg. there is no problem in train station like this
https://osmose.openstreetmap.fr/en/map/#zoom=18&lat=48.876981&lon=2.359684&item=1210&level=1&issue_uuid=4c2a70c6-af53-55d5-4bbf-8ea6c0d56081

But I do net see why.

cc @nlehuby

**Comment by nlehuby** [comment] 2022-11-04 17:48
I do agree : the wording of the issue is not clear, it doesn't really help to find out what is wrong or how to fix it ...

No parking or parking entrance is missing here. And I don't see any error in the data here either, except that it would be nice to continue the drawing (those isolated escalators and stairs are not very useful for routing).
Perhaps the analysis should exclude pedestrian paths (highway=footway & highway=steps) ?

And the issue doesn't raise much on the Île-de-France train stations because the oneway tag is usually not filled in on the escalators. Is it really useful? it is a duplicate of conveying=*, isn't it?

**Comment by Famlam** [comment] 2022-11-05 16:37
But then "one way inaccessible" is still correct, right?

**Comment by brawer** [comment] 2022-11-06 12:43
Would a better visualization of routing islands help? If I understand correctly, Osmose's current analysis is actually right, but the problem is not getting reported in a way that would make sense to users. Specifically, if indoor walking networks were rendered on the map, with routing islands painted in a different color, then the problem report might make more sense. Correct?

**Comment by frodrigo** [comment] 2022-12-21 22:08
> Would a better visualization of routing islands help? If I understand correctly, Osmose's current analysis is actually right, but the problem is not getting reported in a way that would make sense to users. Specifically, if indoor walking networks were rendered on the map, with routing islands painted in a different color, then the problem report might make more sense. Correct?

Yes, this thing would be nice, but too specific for Osmose-QA.

**Closed by frodrigo** 2022-12-21 22:08 UTC
Labels: question
