### ISSUE TITLE
"bug" 30317 in Ukraine

### ISSUE THREAD

**Issue by VARVAR8** [osm-fr/osmose-backend#267] opened 2018-01-29 07:05 UTC
http://osmose.openstreetmap.fr/en/errors/?source=14671&item=3031&class=30317
"Same wikipedia topic on other language" 28298

Ukraine it seems almost always uses both wikipedia=uk:*** and wikipedia:ru=***, yet for some reason, OSMOSE  suggests replacing existing wikipedia=uk:*** tag with wikipedia=ru:***, (while destroying the Ukrainian tag). Please fix this item. Tnks

**Comment by frodrigo** [comment] 2018-01-29 19:30
Duplicate of #233

**Comment by frodrigo** [comment] 2018-01-29 20:23
Add an exception for Ukraine.

**Closed** 2018-01-29 20:25 UTC

**Comment by VARVAR8** [comment] 2018-01-29 23:20
but the markers along with the editor window (wikipedia = ru: ******) on the map still remain.

**Comment by frodrigo** [comment] 2018-02-01 20:26
Done:
http://osmose.openstreetmap.fr/fr/errors/?source=14671&item=3031&class=30317
http://osmose.openstreetmap.fr/fr/errors/graph.png?source=14671&item=3031&class=30317
