### ISSUE TITLE
Disused boundary

### ISSUE THREAD

**Issue by Bibi56** [osm-fr/osmose-backend#683] opened 2019-10-27 15:04 UTC
source | niv | item | cl | scl | E | pos | élmts | sous-titre
-- | -- | -- | -- | -- | -- | -- | -- | --
407663 | 3 | 9007             relation | 9007001 | 881372982 | E | -4.49 48.39 | r          2946277                    (j) | boundary relation sans boundary attribut

Former boundaries have a type boundary but don't have a `boundary`= tag.
They have a `disused:boundary` tag instead.
Can we prevent this false reporting? Should I just note that as false positive instead?

**Comment by Marc-marc-marc** [comment] 2019-11-27 11:01
it should have a boundary=historic

**Comment by Bibi56** [comment] 2019-11-27 11:37
@Marc-marc-marc, good advice.
@frodrigo  (or for the one that will step in ;-)), for disused:boundary, the UI could suggest to add boundary=historic

**Comment by frodrigo** [comment] 2020-01-26 16:43
It is a JOSM MapCSS validator rule.
https://josm.openstreetmap.de/browser/josm/trunk/data/validator/relation.mapcss#L11

cc @Klumbumbus

**Comment by Klumbumbus** [comment] 2020-01-26 17:23
This issue is a duplicate of #631.

I disabled the warning in JOSM now if disused:boundary is present: https://josm.openstreetmap.de/changeset/15771/josm

boundary=historic doesn't sound like a good idea to me as you loose the information which boundary type it was (political, postal_code,...).

**Comment by frodrigo** [comment] 2020-01-26 19:01
Thank

**Closed by frodrigo** 2020-01-26 19:01 UTC
Labels: JOSM MapCSS, bug

**Comment by Klumbumbus** [comment] 2020-01-26 19:07
You're welcom

**Comment by Marc-marc-marc** [comment] 2020-01-26 20:18
> boundary=historic doesn't sound like a good idea to me as you loose the information which boundary type it was (political, postal_code,...).

I dind't understand what is lost with boundary=historic + disused:boundary=oldvalue

**Comment by Klumbumbus** [comment] 2020-01-26 20:20
> I dind't understand what is lost with boundary=historic + disused:boundary=oldvalue
This way nothing. Just if you use boundary=historic only.

**Comment by Marc-marc-marc** [comment] 2020-01-26 20:32
boundary=historic alone is of course is a bad idea.
josm validator may sugest to add the missing boundary=historic and warn in case of boundary=historic without historic=* nor a lifecycle:boundary=* :? )
