### ISSUE TITLE
ref:temples.ru is flagged as error

### ISSUE THREAD

**Issue by ivanbranco** [osm-fr/osmose-backend#1729] opened 2023-01-07 19:33 UTC
item = 3050
class = 30501
link = https://osmose.openstreetmap.fr/it/issues/open?source=18760&item=3050&class=30501

Seems like this tag is flagged as an error even if is a documented tag in the wiki: https://wiki.openstreetmap.org/wiki/Key:ref:temples.ru

**Comment by frodrigo** [comment] 2023-01-07 19:35
Dot `.` is not recommended in key: https://wiki.openstreetmap.org/wiki/Any_tags_you_like#Syntactic_conventions_for_new_tags

> Some characters have special meaning in various context and using these characters in keys will likely cause all sorts of issues. The following characters are among ones discouraged to be used in keys: =, +, /, &, <, > ;, ', ", ?, %, #, @, \, . and ,.

**Comment by Famlam** [comment] 2023-01-08 14:46
I think this is a duplicate of #1055 ?

**Comment by frodrigo** [comment] 2023-01-09 21:19
Yes, duplicate.

**Closed by frodrigo** 2023-01-09 21:19 UTC
Labels: question

**Comment by frodrigo** [comment] 2023-07-22 12:55
Actually we do it.
